### ISSUE TITLE
PyW haalt de console wel weg maar is tijdelijk

### ISSUE THREAD

**Issue by Eldinnie** [Unknowd/MevrouwKamhorstProgramma#20]
Hey Jongens, met [Merge bae73a2](https://github.com/Unknowd/MevrouwKamhorstProgramma/commit/bae73a29e26f4aa927e379da508694e257eae19f#diff-e8436567c6a725c3437279d928a90a96) heb je het programma niet console vrijgemaakt. Alleen start je hem zonder zichtbare console. Jullie moeten als het programma klaar is een package maken met Py2win. Daar hoef je nu nog niet mee bezig te zijn. kan later wel :D

**Comment by PimTH** [comment]
Ah, ik dacht dat die gewoon echt weg was. Als het af is, zullen we dat gebruiken. Bedankt!

**Comment by Eldinnie** [comment]
dan kan je de issue nu sluiten :D
